"""Add fields auto_reply, auto_reply_delay for post

Revision ID: 46cd2dab8079
Revises: fbe66d5833a4
Create Date: 2024-10-24 10:26:02.960026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46cd2dab8079'
down_revision: Union[str, None] = 'fbe66d5833a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('auto_reply', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('auto_reply_delay', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'auto_reply_delay')
    op.drop_column('posts', 'auto_reply')
    # ### end Alembic commands ###
